
[project]
name = "cookietest"
version = "0.1.0"
description = ""
authors = [
	{name = "", email = ""},
]
dependencies = [
    "pytest>=7.4.0",
]
requires-python = ">=3.7"
readme = "README.md"
license = {text = "MIT"}

[project.optional-dependencies]
lint = [
	"ruff>=0.0.275",
	"black>=23.3.0",
	"isort>=5.11.5",
	"mypy>=1.4.1",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
